run:
  timeout: 5m
  issues-exit-code: 1

linters-settings:
  govet:
    check-shadowing: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gosec
    - gocyclo

