import js from '@eslint/js'
import jsdoc from 'eslint-plugin-jsdoc'

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    plugins: {
      jsdoc,
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        WebSocket: 'readonly',
        ResizeObserver: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        ArrayBuffer: 'readonly',
        Uint8Array: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        crypto: 'readonly',
        BroadcastChannel: 'readonly',
        URLSearchParams: 'readonly',
        URL: 'readonly',
        FormData: 'readonly',
        AbortController: 'readonly',
        EventSource: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        console: 'readonly',
        XMLHttpRequest: 'readonly',
        location: 'readonly',
        history: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        DragEvent: 'readonly',
        KeyboardEvent: 'readonly',
        Image: 'readonly',
        HTMLElement: 'readonly',
        DocumentFragment: 'readonly',
      },
    },
    rules: {
      // Catch real bugs and gently nudge contributors toward consistent code.
      'no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      'no-undef': 'error',
      'no-implicit-globals': 'error',
      'no-shadow-restricted-names': 'error',
      'no-redeclare': 'error',
      eqeqeq: ['error', 'smart'],
      curly: ['error', 'multi-line'],
      'no-throw-literal': 'error',
      'no-var': 'error',
      'prefer-const': ['warn', { destructuring: 'all' }],
      'no-debugger': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-with': 'error',

      // JSDoc structural checks. We do not require descriptions on every
      // public symbol (that would be too noisy on a 90% UI codebase); we
      // only flag obviously broken @param / @returns blocks.
      'jsdoc/check-alignment': 'warn',
      'jsdoc/check-param-names': 'warn',
      'jsdoc/check-tag-names': 'warn',
      'jsdoc/check-types': 'warn',
      'jsdoc/no-undefined-types': 'off',
      'jsdoc/require-jsdoc': 'off',
      'jsdoc/require-param-description': 'off',
      'jsdoc/require-returns-description': 'off',
      'jsdoc/valid-types': 'warn',
    },
  },
  {
    // Test / build files can use console freely.
    files: ['src/**/*.test.js', 'src/test/**/*.js'],
    rules: {
      'no-console': 'off',
    },
  },
  { ignores: ['dist', 'node_modules'] },
]
